runtime: nodejs14
service: orange-juice-web
handlers:
  - url: /.*
    secure: always
    script: auto
env_variables:
  MEASUREMENT_ID: "G-2YJ9RM0VEH"
  APP_ID: "1:713270469752:web:b48d4258d4c96ec457f98d"
  MESSAGING_SENDER_ID: "713270469752"
  STORAGE_BUCKET: "orange-juice-prod.appspot.com"
  PROJECT_ID: "orange-juice-prod"
  AUTH_DOMAIN: "orange-juice-prod.firebaseapp.com"
  API_KEY: "AIzaSyAiTLB3S8ah5uo2qOzDfnl2Dx8tplXdCU4"
